'use strict';function A(p,m,l,q){p.B.kc(p.Ua,m,l,q,void 0)}function B(p,m,l){return p.B.ff(p.Ua,m,l)}function J(p,m,l,q){p.B.fa?A(p,m,l,q):p.B.Tf()._OnMessageFromDOM({type:"event",component:p.Ua,handler:m,dispatchOpts:q||null,data:l,responseId:null})}function K(p,m,l){p.B.C(p.Ua,m,l)}function L(p,m){for(const [l,q]of m)K(p,l,q)}window.Ba=class{constructor(p,m){this.B=p;this.Ua=m}jd(){}oa(){}};
window.gf=class{constructor(p,m){this.Od=p;this.lh=m;this.Ka=-1;this.Mb=-Infinity;this.sh=()=>{this.Ka=-1;this.Mb=Date.now();this.Xa=!0;this.Od();this.Xa=!1};this.Pd=this.Xa=!1}};"use strict";function N(p,m){const l=m.elementId,q=p.tb(l,m);p.W.set(l,q);q.style.boxSizing="border-box";m.isVisible||(q.style.display="none");m=p.tc(q);m.addEventListener("focus",()=>{O(p,"elem-focused",l)});m.addEventListener("blur",()=>{O(p,"elem-blurred",l)});p.Eb&&document.body.appendChild(q)}
function P(p,m,l){K(p,m,q=>{const v=p.W.get(q.elementId);return l(v,q)})}function O(p,m,l,q){q||(q={});q.elementId=l;A(p,m,q)}function Q(p,m,l,q){q||(q={});q.elementId=l;J(p,m,q)}
window.fc=class extends self.Ba{constructor(p,m){super(p,m);this.W=new Map;this.Eb=!0;L(this,[["create",l=>N(this,l)],["destroy",l=>{{l=l.elementId;const q=this.W.get(l);this.Eb&&q.parentElement.removeChild(q);this.W.delete(l)}}],["set-visible",l=>{this.Eb&&(this.W.get(l.elementId).style.display=l.isVisible?"":"none")}],["update-position",l=>{if(this.Eb){var q=this.W.get(l.elementId);q.style.left=l.left+"px";q.style.top=l.top+"px";q.style.width=l.width+"px";q.style.height=l.height+"px";l=l.fontSize;
null!==l&&(q.style.fontSize=l+"em")}}],["update-state",l=>{{const q=this.W.get(l.elementId);this.ra(q,l)}}],["focus",l=>this.Dc(l)],["set-css-style",l=>{this.W.get(l.elementId).style[l.prop]=l.val}],["set-attribute",l=>{this.W.get(l.elementId).setAttribute(l.name,l.val)}],["remove-attribute",l=>{this.W.get(l.elementId).removeAttribute(l.name)}]]);P(this,"get-element",l=>l)}tb(){throw Error("required override");}ra(){throw Error("required override");}tc(p){return p}Dc(p){const m=this.tc(this.W.get(p.elementId));
p.focus?m.focus():m.blur()}};"use strict";
{const p=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),m=/android/i.test(navigator.userAgent);let l=0;function q(t){const d=document.createElement("script");d.async=!1;d.type="module";return t.zh?new Promise(n=>{const u="c3_resolve_"+l;++l;self[u]=n;d.textContent=t.Eh+`\n\nself["${u}"]();`;document.head.appendChild(d)}):new Promise((n,u)=>{d.onload=n;d.onerror=u;d.src=t;document.head.appendChild(d)})}let v=!1,G=!1;function k(){if(!v){try{new Worker("blob://",{get type(){G=
!0}})}catch(t){}v=!0}return G}let c=new Audio;const f={"audio/webm; codecs=opus":!!c.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!c.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!c.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!c.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!c.canPlayType("audio/mp4"),"audio/mpeg":!!c.canPlayType("audio/mpeg")};c=null;async function a(t){t=await b(t);return(new TextDecoder("utf-8")).decode(t)}
function b(t){return new Promise((d,n)=>{const u=new FileReader;u.onload=x=>d(x.target.result);u.onerror=x=>n(x);u.readAsArrayBuffer(t)})}const g=[];let r=0;window.RealFile=window.File;const w=[],z=new Map,E=new Map;let F=0;const I=[];self.runOnStartup=function(t){if("function"!==typeof t)throw Error("runOnStartup called without a function");I.push(t)};const e=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.T=class t{constructor(d){this.fa=d.Gh;this.cb=null;this.H="";this.Vb=d.Dh;
this.rb={};this.Tc=this.de=null;this.Ib=[];this.bb=this.N=this.Zc=null;this.Ia=-1;this.qh=()=>this.Cg();this.ce=[];this.j=d.ee;this.Lb="file"===location.protocol.substr(0,4);!this.fa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&k()||(this.fa=!1);if("playable-ad"===this.j||"instant-games"===this.j)this.fa=!1;if("cordova"===this.j&&this.fa)if(m){const n=/Chrome\/(\d+)/i.exec(navigator.userAgent);n&&90<=parseInt(n[1],10)||(this.fa=!1)}else this.fa=!1;this.Rb=this.ha=null;"html5"!==
this.j&&"playable-ad"!==this.j||!this.Lb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");"html5"!==this.j||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",n=>this.hg(n));this.C("runtime",
"create-job-worker",()=>this.ig());"cordova"===this.j?document.addEventListener("deviceready",()=>this.Bd(d)):this.Bd(d)}Te(){return p&&"cordova"===this.j}jc(){const d=navigator.userAgent;return p&&e.has(this.j)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(d)}Qe(){return m}qd(){return m&&e.has(this.j)}async Bd(d){"macos-wkwebview"===this.j&&this.Gc({type:"ready"});if("playable-ad"===this.j){this.ha=self.c3_base64files;this.Rb={};await this.Mf();for(let u=0,x=d.Ma.length;u<x;++u){var n=
d.Ma[u].toLowerCase();this.Rb.hasOwnProperty(n)?d.Ma[u]={zh:!0,Eh:this.Rb[n]}:this.ha.hasOwnProperty(n)&&(d.Ma[u]=URL.createObjectURL(this.ha[n]))}}d.th?this.H=d.th:(n=location.origin,this.H=("null"===n?"file:///":n)+location.pathname,n=this.H.lastIndexOf("/"),-1!==n&&(this.H=this.H.substr(0,n+1)));d.Ih&&(this.rb=d.Ih);n=new MessageChannel;this.cb=n.port1;this.cb.onmessage=u=>this._OnMessageFromRuntime(u.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(u=>this.vg(u));this.bb=
new self.Ue(this);await R(this.bb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.fa?await this.Zf(d,n.port2):await this.Yf(d,n.port2)}uc(d){d=this.rb.hasOwnProperty(d)?this.rb[d]:d.endsWith("/workermain.js")&&this.rb.hasOwnProperty("workermain.js")?this.rb["workermain.js"]:"playable-ad"===this.j&&this.ha.hasOwnProperty(d.toLowerCase())?this.ha[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));
return d}async ec(d,n,u){if(d.startsWith("blob:"))return new Worker(d,u);if("cordova"===this.j&&this.Lb)return d=await this.dc(u.yh?d:this.Vb+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),u);d=new URL(d,n);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();return new Worker(URL.createObjectURL(d),u)}return new Worker(d,u)}pa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,
1)}zd(d){var n=this.bb;return{baseUrl:this.H,windowInnerWidth:this.pa(),windowInnerHeight:this.ga(),devicePixelRatio:window.devicePixelRatio,isFullscreen:t.Oa(),projectData:d.Ph,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Nh||"",exportType:d.ee,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Oh,jobScheduler:{inputPort:n.Pc,outputPort:n.Xc,maxNumWorkers:n.nh},
supportedAudioFormats:f,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Vb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Vb+"opus.wasm.wasm",isFileProtocol:this.Lb,isiOSCordova:this.Te(),isiOSWebView:this.jc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Zf(d,n){var u=this.uc(d.Hh);this.de=await this.ec(u,this.H,{type:"module",name:"Runtime",yh:!0});this.N=document.createElement("canvas");this.N.style.display="none";u=this.N.transferControlToOffscreen();
document.body.appendChild(this.N);window.c3canvas=this.N;let x=d.gd||[],D=d.Ma;x=await Promise.all(x.map(y=>this.Da(y)));D=await Promise.all(D.map(y=>this.Da(y)));if("cordova"===this.j)for(let y=0,C=d.bc.length;y<C;++y){const H=d.bc[y],M=H[0];if(M===d.ed||"scriptsInEvents.js"===M||M.endsWith("/scriptsInEvents.js"))H[1]=await this.Da(M)}this.de.postMessage(Object.assign(this.zd(d),{type:"init-runtime",isInWorker:!0,messagePort:n,canvas:u,workerDependencyScripts:x,engineScripts:D,projectScripts:d.bc,
mainProjectScript:d.ed,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[n,u,...S(this.bb)]);this.Ib=w.map(y=>new y(this));this.yd();self.c3_callFunction=(y,C)=>this.Zc.$f(y,C);"preview"===this.j&&(self.goToLastErrorScript=()=>this.kc("runtime","go-to-last-error-script"))}async Yf(d,n){this.N=document.createElement("canvas");this.N.style.display="none";document.body.appendChild(this.N);window.c3canvas=this.N;this.Ib=w.map(y=>new y(this));this.yd();var u=d.Ma.map(y=>"string"===typeof y?(new URL(y,
this.H)).toString():y);Array.isArray(d.gd)&&u.unshift(...d.gd);u=await Promise.all(u.map(y=>this.Da(y)));await Promise.all(u.map(y=>q(y)));u=self.C3_ProjectScriptsStatus;const x=d.ed,D=d.bc;for(let [y,C]of D)if(C||(C=y),y===x)try{C=await this.Da(C),await q(C),"preview"!==this.j||u[y]||this.Jd(y,"main script did not run to completion")}catch(H){this.Jd(y,H)}else if("scriptsInEvents.js"===y||y.endsWith("/scriptsInEvents.js"))C=await this.Da(C),await q(C);"preview"===this.j&&"object"!==typeof self.Jh.Kh?
(this.Cb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this.zd(d),{isInWorker:!1,messagePort:n,canvas:this.N,runOnStartupFunctions:I}),this.Dd(),this.Tc=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.Tc,d))}Jd(d,n){this.Cb();console.error(`[Preview] Failed to load project main script (${d}): `,
n);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Dd(){this.Cb()}Cb(){const d=window.vh;d&&(d.parentElement.removeChild(d),window.vh=null)}async ig(){const d=await U(this.bb);return{outputPort:d,transferables:[d]}}Tf(){if(this.fa)throw Error("not available in worker mode");return this.Tc}kc(d,n,u,x,D){this.cb.postMessage({type:"event",component:d,handler:n,dispatchOpts:x||null,data:u,responseId:null},
D)}ff(d,n,u){const x=F++,D=new Promise((y,C)=>{E.set(x,{resolve:y,reject:C})});this.cb.postMessage({type:"event",component:d,handler:n,dispatchOpts:null,data:u,responseId:x},void 0);return D}["_OnMessageFromRuntime"](d){const n=d.type;if("event"===n)return this.ng(d);if("result"===n)this.Fg(d);else if("runtime-ready"===n)this.Gg();else if("alert-error"===n)this.Cb(),alert(d.message);else if("creating-runtime"===n)this.Dd();else throw Error(`unknown message '${n}'`);}ng(d){const n=d.component,u=d.handler,
x=d.data,D=d.responseId;if(d=z.get(n))if(d=d.get(u)){var y=null;try{y=d(x)}catch(C){console.error(`Exception in '${n}' handler '${u}':`,C);null!==D&&this.Bb(D,!1,""+C);return}if(null===D)return y;y&&y.then?y.then(C=>this.Bb(D,!0,C)).catch(C=>{console.error(`Rejection from '${n}' handler '${u}':`,C);this.Bb(D,!1,""+C)}):this.Bb(D,!0,y)}else console.warn(`[DOM] No handler '${u}' for component '${n}'`);else console.warn(`[DOM] No event handlers for component '${n}'`)}Bb(d,n,u){let x;u&&u.transferables&&
(x=u.transferables);this.cb.postMessage({type:"result",responseId:d,isOk:n,result:u},x)}Fg(d){const n=d.responseId,u=d.isOk;d=d.result;const x=E.get(n);u?x.resolve(d):x.reject(d);E.delete(n)}C(d,n,u){let x=z.get(d);x||(x=new Map,z.set(d,x));if(x.has(n))throw Error(`[DOM] Component '${d}' already has handler '${n}'`);x.set(n,u)}static ka(d){if(w.includes(d))throw Error("DOM handler already added");w.push(d)}yd(){for(const d of this.Ib)if("runtime"===d.Ua){this.Zc=d;return}throw Error("cannot find runtime DOM handler");
}vg(d){this.kc("debugger","message",d)}Gg(){for(const d of this.Ib)d.jd()}static Oa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||h)}static Db(d){h=!!d}Kd(){-1===this.Ia&&this.ce.length&&(this.Ia=requestAnimationFrame(this.qh))}If(){-1!==this.Ia&&(cancelAnimationFrame(this.Ia),this.Ia=-1)}Cg(){this.Ia=-1;for(const d of this.ce)d();this.Kd()}Fc(){this.Zc.Fc()}Pe(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,
5)}Re(d){return!this.Pe(d)}async Da(d){return"cordova"===this.j&&(d.startsWith("file:")||this.Lb&&this.Re(d))?(d.startsWith(this.H)&&(d=d.substr(this.H.length)),d=await this.dc(d),URL.createObjectURL(new Blob([d],{type:"application/javascript"}))):d}async hg(d){const n=d.filename;switch(d.as){case "text":return await this.ve(n);case "buffer":return await this.dc(n);default:throw Error("unsupported type");}}nd(d){const n=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((u,
x)=>{window.resolveLocalFileSystemURL(n,D=>{D.file(u,x)},x)})}async ve(d){d=await this.nd(d);return await a(d)}sc(){if(g.length&&!(8<=r)){r++;var d=g.shift();this.Nf(d.filename,d.Fh,d.wh)}}dc(d){return new Promise((n,u)=>{g.push({filename:d,Fh:x=>{r--;this.sc();n(x)},wh:x=>{r--;this.sc();u(x)}});this.sc()})}async Nf(d,n,u){try{const x=await this.nd(d),D=await b(x);n(D)}catch(x){u(x)}}Gc(d){if("windows-webview2"===this.j)window.chrome.webview.postMessage(JSON.stringify(d));else if("macos-wkwebview"===
this.j)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(d));else throw Error("cannot send wrapper message");}async Mf(){const d=[];for(const [n,u]of Object.entries(this.ha))d.push(this.Lf(n,u));await Promise.all(d)}async Lf(d,n){if("object"===typeof n)this.ha[d]=new Blob([n.str],{type:n.type}),this.Rb[d]=n.str;else{let u=await this.Rf(n);u||(u=this.Of(n));this.ha[d]=u}}async Rf(d){try{return await (await fetch(d)).blob()}catch(n){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
n),null}}Of(d){d=this.$g(d);return this.Hf(d.data,d.Ah)}$g(d){var n=d.indexOf(",");if(0>n)throw new URIError("expected comma in data: uri");var u=d.substring(n+1);n=d.substring(5,n).split(";");d=n[0]||"";const x=n[2];u="base64"===n[1]||"base64"===x?atob(u):decodeURIComponent(u);return{Ah:d,data:u}}Hf(d,n){var u=d.length;let x=u>>2,D=new Uint8Array(u),y=new Uint32Array(D.buffer,0,x),C,H;for(H=C=0;C<x;++C)y[C]=d.charCodeAt(H++)|d.charCodeAt(H++)<<8|d.charCodeAt(H++)<<16|d.charCodeAt(H++)<<24;for(u&=
3;u--;)D[H]=d.charCodeAt(H),++H;return new Blob([D],{type:n})}}}"use strict";
{const p=self.T;function m(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const l=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),q={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},v={dispatchUserScriptEvent:!0},G={dispatchRuntimeEvent:!0};function k(e){return new Promise((h,t)=>{const d=document.createElement("link");d.onload=()=>h(d);d.onerror=n=>t(n);d.rel=
"stylesheet";d.href=e;document.head.appendChild(d)})}function c(e){return new Promise((h,t)=>{const d=new Image;d.onload=()=>h(d);d.onerror=n=>t(n);d.src=e})}async function f(e){e=URL.createObjectURL(e);try{return await c(e)}finally{URL.revokeObjectURL(e)}}function a(e){return new Promise((h,t)=>{let d=new FileReader;d.onload=n=>h(n.target.result);d.onerror=n=>t(n);d.readAsText(e)})}async function b(e,h,t){if(!/firefox/i.test(navigator.userAgent))return await f(e);var d=await a(e);d=(new DOMParser).parseFromString(d,
"image/svg+xml");const n=d.documentElement;if(n.hasAttribute("width")&&n.hasAttribute("height")){const u=n.getAttribute("width"),x=n.getAttribute("height");if(!u.includes("%")&&!x.includes("%"))return await f(e)}n.setAttribute("width",h+"px");n.setAttribute("height",t+"px");d=(new XMLSerializer).serializeToString(d);e=new Blob([d],{type:"image/svg+xml"});return await f(e)}function g(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const r=new Set(["input",
"textarea","datalist","select"]),w=new Set(["canvas","body","html"]);function z(e){w.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function E(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await f(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,t,d,n){e=await b(e,h,t);const u=document.createElement("canvas");u.width=d;u.height=n;u.getContext("2d").drawImage(e,0,0,h,t);return u};let F=!1;document.addEventListener("pause",()=>F=!0);document.addEventListener("resume",()=>F=!1);function I(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}p.ka(class extends self.Ba{constructor(e){super(e,"runtime");this.Ud=!0;this.Ja=-1;this.cd="any";this.Ld=this.Md=!1;this.Ga=
this.jb=this.xa=null;this.Tb=this.Sb=0;this.$d=e.pa();this.Pb=e.ga();this.pb=0;e.C("canvas","update-size",d=>this.Xg(d));e.C("runtime","invoke-download",d=>this.tg(d));e.C("runtime","raster-svg-image",d=>this.Dg(d));e.C("runtime","get-svg-image-size",d=>this.pg(d));e.C("runtime","set-target-orientation",d=>this.Ig(d));e.C("runtime","register-sw",()=>this.Eg());e.C("runtime","post-to-debugger",d=>this.Hd(d));e.C("runtime","go-to-script",d=>this.Hd(d));e.C("runtime","before-start-ticking",()=>this.eg());
e.C("runtime","debug-highlight",d=>this.jg(d));e.C("runtime","enable-device-orientation",()=>this.Gf());e.C("runtime","enable-device-motion",()=>this.Ff());e.C("runtime","add-stylesheet",d=>this.cg(d));e.C("runtime","alert",d=>this.xc(d));e.C("runtime","hide-cordova-splash",()=>this.qg());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const n=d.target;h.has(n.tagName.toLowerCase())||g(n)||d.preventDefault()});const t=e.N;window.addEventListener("selectstart",
z);window.addEventListener("gesturehold",z);t.addEventListener("selectstart",z);t.addEventListener("gesturehold",z);window.addEventListener("touchstart",z,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),t.addEventListener("pointerdown",z)):t.addEventListener("touchstart",z);this.eb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",E,{passive:!1});window.addEventListener("wheel",E,
{passive:!1});window.addEventListener("resize",()=>this.Yg());window.addEventListener("fullscreenchange",()=>this.Ra());window.addEventListener("webkitfullscreenchange",()=>this.Ra());window.addEventListener("mozfullscreenchange",()=>this.Ra());window.addEventListener("fullscreenerror",d=>this.Ac(d));window.addEventListener("webkitfullscreenerror",d=>this.Ac(d));window.addEventListener("mozfullscreenerror",d=>this.Ac(d));e.jc()&&window.addEventListener("focusout",()=>{{const u=document.activeElement;
if(u){var d=u.tagName.toLowerCase();var n=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?n.has(u.type.toLowerCase()||"text"):g(u)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>this.Zg(d);this.Uc=new Set;this.oh=new WeakSet;this.mh=!1}eg(){"cordova"===this.B.j?(document.addEventListener("pause",()=>this.Ec(!0)),document.addEventListener("resume",()=>this.Ec(!1))):document.addEventListener("visibilitychange",()=>this.Ec(document.hidden));
return{isSuspended:!(!document.hidden&&!F)}}jd(){window.addEventListener("focus",()=>this.Ta("window-focus"));window.addEventListener("blur",()=>{this.Ta("window-blur",{parentHasFocus:I()});this.eb=0});window.addEventListener("focusin",h=>{h=h.target;(r.has(h.tagName.toLowerCase())||g(h))&&this.Ta("keyboard-blur")});window.addEventListener("keydown",h=>this.Ed("keydown",h));window.addEventListener("keyup",h=>this.Ed("keyup",h));window.addEventListener("dblclick",h=>this.Bc("dblclick",h,q));window.addEventListener("wheel",
h=>this.wg(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",h=>{this.vc(h);this.Sa("pointerdown",h)}),this.B.fa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.jb=new self.gf(()=>this.Qf(),5),this.jb.Pd=!0,window.addEventListener("pointerrawupdate",h=>this.Ag(h))):window.addEventListener("pointermove",h=>this.Sa("pointermove",h)),window.addEventListener("pointerup",h=>this.Sa("pointerup",h)),window.addEventListener("pointercancel",h=>this.Sa("pointercancel",
h))):(window.addEventListener("mousedown",h=>{this.vc(h);this.Cc("pointerdown",h)}),window.addEventListener("mousemove",h=>this.Cc("pointermove",h)),window.addEventListener("mouseup",h=>this.Cc("pointerup",h)),window.addEventListener("touchstart",h=>{this.vc(h);this.Ab("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Ab("pointermove",h)),window.addEventListener("touchend",h=>this.Ab("pointerup",h)),window.addEventListener("touchcancel",h=>this.Ab("pointercancel",h)));const e=()=>this.Fc();
window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0);this.B.Qe()&&!this.B.qd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this.yc(this.ga(),navigator.virtualKeyboard.boundingRect.height)}))}yc(e,h){document.body.style.transform="";if(0<h){var t=document.activeElement;
t&&(t=t.getBoundingClientRect(),e=(t.top+t.bottom)/2-(e-h)/2,e>h&&(e=h),0>e&&(e=0),0<e&&(document.body.style.transform=`translateY(${-e}px)`))}}Ta(e,h){A(this,e,h||null,G)}pa(){return this.B.pa()}ga(){return this.B.ga()}Yg(){const e=this.pa(),h=this.ga();if(this.B.qd()){if(this.$d===e&&h<this.Pb){this.pb=this.Pb-h;this.yc(this.Pb,this.pb);return}0<this.pb&&(this.pb=0,this.yc(h,this.pb));this.$d=e;this.Pb=h}this.Ta("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,
isFullscreen:p.Oa()});this.B.jc()&&(-1!==this.Ja&&clearTimeout(this.Ja),this.Id(e,h,0))}bh(e,h,t){-1!==this.Ja&&clearTimeout(this.Ja);this.Ja=setTimeout(()=>this.Id(e,h,t),48)}Id(e,h,t){const d=this.pa(),n=this.ga();this.Ja=-1;d!=e||n!=h?this.Ta("window-resize",{innerWidth:d,innerHeight:n,devicePixelRatio:window.devicePixelRatio,isFullscreen:p.Oa()}):10>t&&this.bh(d,n,t+1)}Ig(e){this.cd=e.targetOrientation}jh(){const e=this.cd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>
console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Ra(){const e=p.Oa();e&&"any"!==this.cd&&this.jh();A(this,"fullscreenchange",
{isFullscreen:e,innerWidth:this.pa(),innerHeight:this.ga()})}Ac(e){console.warn("[Construct 3] Fullscreen request failed: ",e);A(this,"fullscreenerror",{isFullscreen:p.Oa(),innerWidth:this.pa(),innerHeight:this.ga()})}Ec(e){e?this.B.If():this.B.Kd();A(this,"visibilitychange",{hidden:e})}Ed(e,h){"Backspace"===h.key&&z(h);const t=l.get(h.code)||h.code;J(this,e,{code:t,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},
q)}wg(e){A(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,timeStamp:e.timeStamp},q)}Bc(e,h,t){m(h)||J(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,timeStamp:h.timeStamp},t)}Cc(e,h){if(!m(h)){var t=this.eb;"pointerdown"===e&&0!==t?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");
J(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:t,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},q);this.eb=h.buttons;this.Bc(h.type,h,v)}}Sa(e,h){if(this.jb&&"pointermove"!==e){var t=this.jb;t.Xa||(-1!==t.Ka&&(self.clearTimeout(t.Ka),t.Ka=-1),t.Mb=Date.now())}t=0;"mouse"===h.pointerType&&(t=this.eb);
J(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:t,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,movementX:(h.movementX||0)+this.Sb,movementY:(h.movementY||0)+this.Tb,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},q);this.Tb=this.Sb=0;"mouse"===h.pointerType&&(t="mousemove","pointerdown"===e?t="mousedown":
"pointerup"===e&&(t="mouseup"),this.Bc(t,h,v),this.eb=h.buttons)}Ag(e){this.Ga&&(this.Sb+=this.Ga.movementX||0,this.Tb+=this.Ga.movementY||0);this.Ga=e;e=this.jb;if(-1===e.Ka){var h=Date.now(),t=h-e.Mb,d=e.lh;t>=d&&e.Pd?(e.Mb=h,e.Xa=!0,e.Od(),e.Xa=!1):e.Ka=self.setTimeout(e.sh,Math.max(d-t,4))}}Qf(){this.Sa("pointermove",this.Ga);this.Ga=null}Ab(e,h){for(let t=0,d=h.changedTouches.length;t<d;++t){const n=h.changedTouches[t];J(this,e,{pointerId:n.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,
clientX:n.clientX,clientY:n.clientY,pageX:n.pageX,pageY:n.pageY,movementX:h.movementX||0,movementY:h.movementY||0,width:2*(n.radiusX||n.webkitRadiusX||0),height:2*(n.radiusY||n.webkitRadiusY||0),pressure:n.force||n.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:n.rotationAngle||0,timeStamp:h.timeStamp},q)}}vc(e){window!==window.top&&window.focus();this.Cd(e.target)&&document.activeElement&&!this.Cd(document.activeElement)&&document.activeElement.blur()}Cd(e){return!e||e===document||e===
window||e===document.body||"canvas"===e.tagName.toLowerCase()}Gf(){this.Md||(this.Md=!0,window.addEventListener("deviceorientation",e=>this.lg(e)),window.addEventListener("deviceorientationabsolute",e=>this.mg(e)))}Ff(){this.Ld||(this.Ld=!0,window.addEventListener("devicemotion",e=>this.kg(e)))}lg(e){A(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},
q)}mg(e){A(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},q)}kg(e){let h=null;var t=e.acceleration;t&&(h={x:t.x||0,y:t.y||0,z:t.z||0});t=null;var d=e.accelerationIncludingGravity;d&&(t={x:d.x||0,y:d.y||0,z:d.z||0});d=null;const n=e.rotationRate;n&&(d={alpha:n.alpha||0,beta:n.beta||0,gamma:n.gamma||0});A(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:t,rotationRate:d,interval:e.interval,timeStamp:e.timeStamp},
q)}Xg(e){const h=this.B.N;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Ud&&(h.style.display="",this.Ud=!1)}tg(e){const h=e.url;e=e.filename;const t=document.createElement("a"),d=document.body;t.textContent=e;t.href=h;t.download=e;d.appendChild(t);t.click();d.removeChild(t)}async Dg(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);
h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async pg(e){return await self.C3_GetSvgImageSize(e.blob)}async cg(e){await k(e.url)}Fc(){var e=[...this.Uc];this.Uc.clear();if(!this.mh)for(const h of e)(e=h.play())&&e.catch(()=>{this.oh.has(h)||this.Uc.add(h)})}qg(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}jg(e){if(e.show){this.xa||(this.xa=document.createElement("div"),this.xa.id="inspectOutline",document.body.appendChild(this.xa));
var h=this.xa;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.xa&&(this.xa.style.display="none")}Eg(){window.C3_RegisterSW&&window.C3_RegisterSW()}Hd(e){window.c3_postToMessagePort&&(e.from="runtime",window.c3_postToMessagePort(e))}$f(e,h){return B(this,"js-invoke-function",{name:e,params:h})}xc(e){alert(e.message)}Zg(e){"entered-fullscreen"===e?(p.Db(!0),this.Ra()):"exited-fullscreen"===
e?(p.Db(!1),this.Ra()):console.warn("Unknown wrapper message: ",e)}})}"use strict";async function R(p){if(p.kh)throw Error("already initialised");p.kh=!0;var m=p.Ub.uc("dispatchworker.js");p.Jc=await p.Ub.ec(m,p.H,{name:"DispatchWorker"});m=new MessageChannel;p.Pc=m.port1;p.Jc.postMessage({type:"_init","in-port":m.port2},[m.port2]);p.Xc=await U(p)}function S(p){return[p.Pc,p.Xc]}
async function U(p){const m=p.Vd.length;var l=p.Ub.uc("jobworker.js");l=await p.Ub.ec(l,p.H,{name:"JobWorker"+m});const q=new MessageChannel,v=new MessageChannel;p.Jc.postMessage({type:"_addJobWorker",port:q.port1},[q.port1]);l.postMessage({type:"init",number:m,"dispatch-port":q.port2,"output-port":v.port2},[q.port2,v.port2]);p.Vd.push(l);return v.port1}
self.Ue=class{constructor(p){this.Ub=p;this.H=p.H;this.H="preview"===p.j?this.H+"workers/":this.H+p.Vb;this.nh=Math.min(navigator.hardwareConcurrency||2,16);this.Jc=null;this.Vd=[];this.Xc=this.Pc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.T({Gh:!0,Hh:"workermain.js",Ma:["scripts/c3runtime.js"],bc:[],ed:"",Dh:"scripts/",gd:[],ee:"html5"}));"use strict";
{const p=[],m=2*Math.PI;function l(c){c%=m;0>c&&(c+=m);return c}class q{constructor(c,f,a,b,g,r){this.Sd=c;this.Ya=f;this.qa=a;this.ob=b;this.Zb=g;this.Qd=r}Ca(){return{tag:this.ob,interp:this.Ya,userData:this.Zb,cvt:this.Qd}}ma(){return this.Ya}Ne(){return"undefined"!==typeof this.Zb}ld(c){switch(this.qa){case 0:return c;case 1:return Math.fround(c);case 2:return 2===this.Ya&&(c=l(c),c/=Math.PI,c=32767*(c-1)),c|=0,-32768>c?-32768:32767<c?32767:c;case 3:return 2===this.Ya&&(c=l(c),c/=m,c*=255),c|=
0,0>c?0:255<c?255:c;default:return c}}vd(c,f,a){switch(this.qa){case 0:c.setFloat64(f,a);f+=8;break;case 1:c.setFloat32(f,a);f+=4;break;case 2:c.setInt16(f,a);f+=2;break;case 3:c.setUint8(f,a);f+=1;break;default:c.setFloat32(f,a),f+=4}return f}yb(c){if(2!==this.Ya)return c;2===this.qa?c=(c/32767+1)*Math.PI:3===this.qa&&(c=c/255*m);return c}static wb(c,f,a,b,g){switch(c){case 0:return g?a:f;case 1:return f+b*(a-f);case 2:return f===a?c=0:(c=Math.sin(f)*Math.sin(a)+Math.cos(f)*Math.cos(a),c=1<=c?0:
-1>=c?Math.PI:Math.acos(c)),f=0>=Math.cos(a)*Math.sin(f)-Math.sin(a)*Math.cos(f)?l(f+c*b):l(f-c*b);default:return g?a:f}}}class v{constructor(c,f){this.timestamp=c;this.data=f}}class G{constructor(c,f,a){this.P=c;this.b=c.b;this.l=f;this.F=a;this.Va=[];this.Va.length=this.P.S.length;this.Sc=this.Nb=0;this.Td=this.Xb=!1;this.I=[];this.s=this.h=this.Y=null}Ca(){var c=[];for(let a=0,b=this.P.S.length;a<b;++a)c.push(this.ma(this.P.Wb,a));c={id:this.l,nid:this.F,isTimedOut:this.Se(),interpValues:c,latestUpdate:null};
const f=this.Ee();f&&(c.latestUpdate={timestamp:f.timestamp,data:f.data});return c}sd(c){this.Td=!!c}qc(c,f){c=c.netValues;var a=this.P.S;const b=a.length;this.Xb=!1;for(let g=0;g<b;++g){const r=a[g].ld(c[g]);this.Va[g]!==r&&(this.Va[g]=r,this.Nb=f,this.P.mf(f))}c=f-this.Nb;f-=this.Sc;a=this.P.Nd;(this.Xb=100>c&&0===a?!0:1E3>c&&1>=a?95<=f:495<=f)&&this.P.Oe()}rc(c,f,a){const b=this.P.S;this.Sc=a;c.setUint16(f,this.F);f+=2;for(let g=0,r=this.Va.length;g<r;++g)f=b[g].vd(c,f,this.Va[g]);return f}cc(c,
f){for(let a=0,b=this.I.length;a<b;++a){const g=this.I[a];if(g.timestamp===c)return;if(g.timestamp>c){this.I.splice(a,0,new v(c,f));return}}this.I.push(new v(c,f))}Se(){return 0===this.I.length?!1:this.I[this.I.length-1].timestamp<this.P.Wb-3E3}oa(){for(;2<this.I.length&&this.I[0]!==this.Y&&this.I[0]!==this.h&&this.I[0]!==this.s;)this.I.shift();const c=this.P.Wb;if(!(this.s&&this.s.timestamp>c&&this.h&&this.h.timestamp<c)){this.s=null;for(let f=0,a=this.I.length;f<a;++f){const b=this.I[f];if(b.timestamp<=
c){if(!this.h||b.timestamp>this.h.timestamp)this.Y=this.h,this.h=b}else{this.s=b;break}}}}Ee(){return 0===this.I.length?null:this.I[this.I.length-1]}ma(c,f){if(!this.s&&!this.h)return 0;if(this.s&&!this.h)return this.s.data[f];const a=this.P.S;let b,g,r;if(!this.s&&this.h){if(this.Y){var w=this.Y.timestamp;b=this.Y.data[f];g=this.h.timestamp;r=this.h.data[f];c>this.h.timestamp+this.P.Kb&&(c=this.h.timestamp+this.P.Kb);w=w===g?0:(c-w)/(g-w);return q.wb(a[f].ma(),b,r,w,!0)}return this.h.data[f]}w=this.h.timestamp;
b=this.h.data[f];g=this.s.timestamp;r=this.s.data[f];w=w===g?0:(c-w)/(g-w);return q.wb(a[f].ma(),b,r,w,!1)}}class k{constructor(c,f,a,b){this.b=c;this.mb=f;this.nb=a;this.F=this.b.Ie();this.Nd=b;this.Zb={};this.ca=0;this.Kb=250;switch(this.Nd){case 1:this.Kb=500;break;case 2:this.Kb=2500}this.S=[];this.X=[];this.ya=new Map;this.La=new Set;this.hb=this.Sc=this.Nb=this.fb=0;this.Fa=!1;this.Hb=[];this.gb=new Map;this.Wb=0;this.b.oe(this)}ta(c){this.F=c}mf(c){this.Nb=c}Oe(){this.hb++}gh(){this.Fa=!0}la(c,
f,a,b,g){c=new q(this.S.length,c,f,a,b,g);switch(f){case 0:this.ca+=8;break;case 1:this.ca+=4;break;case 2:this.ca+=2;break;case 3:this.ca+=1}this.S.push(c)}cc(c,f,a){this.Ge(f).cc(c,a)}oa(){this.Wb=this.b.vb();for(const c of this.X)c.oa()}He(){const c=[];for(const f of this.S){const a={tag:f.ob,precision:f.qa,interp:f.ma(),clientvaluetag:f.Qd};f.Ne()&&(a.userdata=f.Zb);c.push(a)}return c}pf(c){this.ca=this.S.length=0;for(const f of c)this.la(f.interp,f.precision,f.tag,f.userdata,f.clientvaluetag)}Ge(c){let f=
this.gb.get(c);if(f)return f;f=new G(this,-1,c);this.gb.set(c,f);this.X.push(f);return f}Fe(c){let f=this.ya.get(c);if(f)return f;f=new G(this,c,this.qe());this.ya.set(c,f);this.X.push(f);return f}qe(){do this.fb++,65535<this.fb&&(this.fb=0);while(this.La.has(this.fb));const c=this.fb;this.La.add(c);return c}lc(c){const f=c.l,a=c.F;this.b.g()&&!this.Fa&&this.Hb.push(a);this.ya.delete(f);this.gb.delete(a);this.La.delete(a);c=this.X.indexOf(c);-1<c&&this.X.splice(c,1)}ue(){this.Hb.length=0;this.ya.clear();
this.gb.clear();this.La.clear();this.X.length=0}qc(c,f){this.hb=0;for(var a of this.X)a.sd(!1);for(let b=0,g=c.length;b<g;++b){a=c[b];const r=this.Fe(a.uid);r.sd(!0);r.qc(a,f)}for(const b of this.X)b.Td||p.push(b);for(const b of p)this.lc(b);p.length=0}rc(c,f,a){c.setUint16(f,this.F);f+=2;let b=0;this.Fa&&(b=1);c.setUint8(f,b);f+=1;c.setUint16(f,this.hb);f+=2;c.setUint16(f,this.ca);f+=2;for(const g of this.X)g.Xb&&(f=g.rc(c,f,a));return f}ef(c,f){if(this.ya.has(c))console.warn("OverrideNid passed id "+
c+" which is already in use and cannot be overridden");else if(this.La.has(f))console.warn("OverrideNid passed nid "+f+" which is already in use and cannot be overridden");else{var a=new G(this,c,f);this.ya.set(c,a);this.La.add(f);this.X.push(a);this.Fa=!0}}mc(c){(c=this.ya.get(c))&&this.lc(c)}nc(c){(c=this.gb.get(c))&&this.lc(c)}Ca(){return{hasOverriddenNids:this.Fa,netValues:this.S.map(c=>c.Ca()),netInstances:this.X.map(c=>c.Ca())}}Ke(){return{roId:this.mb,sid:this.nb,netValues:this.S.map(c=>c.Ca())}}}
self.kd=q;self.re=v;self.te=k}"use strict";
{const p=self.re,m=self.kd,l=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection;function q(k){if(k)try{k.close()}catch(c){}}const v=[];class G{constructor(k,c,f){this.b=k;this.l=c;this.F=0;this.K=f;this.ua=this.o=null;this.Za=!1;this.va=null;this.$a=!1;this.wa=null;this.Mc=this.qb=this.Wa=this.Ea=this.ab=!1;this.Jb=this.Rd=this.Qc=0;this.ae=[];this.Yd=this.Xd=0;this.R=[];this.s=this.h=this.Y=null;this.Wd=0;this.Hc=!1;this.Rc=1;this.Ob=
[];this.be=this.Qb=0;this.b.Ef(this)}ta(k){this.F=k}g(){return this===this.b.A}xb(){return this===this.b.v}hh(){this.Xd=performance.now()}ih(k){this.Yd=k}zb(k,c){k.binaryType="arraybuffer";k.onopen=()=>{"o"===c?this.Za=!0:"r"===c?this.$a=!0:"u"===c&&(this.ab=!0);this.bg()};k.onmessage=f=>{this.ug(c,f)};k.onerror=f=>{console.error("Peer '"+this.l+"' datachannel '"+c+"' error: ",f);this.b.$(this,f);this.b.g()&&!this.g()&&this.D("network error")};k.onclose=()=>{this.D("disconnect")}}md(){if(!this.xb()){var k=
this.b.g();this.Wa=this.Ea=this.ab=this.$a=this.Za=!1;this.Rd=performance.now();this.o=new l({iceServers:this.b.Oc});this.o.onicecandidate=f=>{f.candidate&&this.b.Z({message:"icecandidate",toclientid:this.l,icecandidate:f.candidate})};this.o.onsignalingstatechange=()=>{this.o&&"closed"===this.o.signalingState&&this.D("disconnect")};this.o.oniceconnectionstatechange=()=>{this.o&&("failed"!==this.o.iceConnectionState&&"closed"!==this.o.iceConnectionState||this.D("disconnect"))};this.o.onconnectionstatechange=
()=>{if(this.o){var f=this.o.connectionState;"failed"!==f&&"closed"!==f||this.D("disconnect")}};var c=`c2mp_${this.b.ze()}_${this.b.Ae()}_${this.b.Be()}`;k?(this.F=this.b.hd(),this.ua=this.o.createDataChannel("o",{ordered:!0,protocol:c}),this.zb(this.ua,"o"),this.va=this.o.createDataChannel("r",{ordered:!1,protocol:c}),this.zb(this.va,"r"),this.wa=this.o.createDataChannel("u",{ordered:!1,maxRetransmits:0,protocol:c}),this.zb(this.wa,"u"),this.o.createOffer().then(f=>{this.o.setLocalDescription(f);
this.b.Z({message:"offer",toclientid:this.l,offer:f})}).catch(f=>{console.error("Host error creating offer for peer '"+this.l+"': ",f);this.b.$(this,"could not create offer for peer")})):this.o.ondatachannel=f=>{if(f.channel.protocol!==c)console.error("Unexpected datachannel protocol '"+f.channel.protocol+"', should be '"+c+"'"),this.b.$(this,"unexpected datachannel protocol '"+f.channel.protocol+"', should be '"+c+"'");else{var a=f.channel.label;"o"===a?this.ua=f.channel:"r"===a?this.va=f.channel:
"u"===a?this.wa=f.channel:(console.error("Unknown datachannel label: "+f.channel.label),this.b.$(this,"unknown datachannel label '"+f.channel.label+"'"));this.zb(f.channel,a)}}}}async Df(k){if(this.o)try{await this.o.addIceCandidate(k)}catch(c){console.warn("[Multiplayer] Error adding ICE candidate: ",c)}}Me(){return!!this.o}bg(){!this.Ea&&this.$a&&this.ab&&this.Za&&(this.xg(),this.Ea=!0,this.Wa=!1)}xg(){this.Qc=performance.now();if(this.b.g()){this.b.Na("o",JSON.stringify({c:"j",i:this.l,n:this.F,
a:this.K}),this);this.na("o",JSON.stringify({c:"hi",hn:this.b.A.F,n:this.F,d:this.b.V,u:this.b.ib,objs:this.b.Je(),cvs:this.b.ye()}));for(const k of this.b.ba)!k.g()&&k!==this&&k.ic()&&this.na("o",JSON.stringify({c:"j",i:k.l,n:k.F,a:k.K}))}else this.Mc=!0,this.g()&&this.oc(performance.now(),!0);this.b.Gd(this)}ag(k){!this.Wa&&this.Ea&&(this.zc(k),this.Wa=!0,this.Ea=!1)}zc(k){this.b.g()&&!this.xb()&&this.b.Na("o",JSON.stringify({c:"l",i:this.l,a:this.K,r:k}),this);this.xb()||this.b.Fd(this,k)}ic(){return this.Ea&&
!this.Wa}na(k,c){this.b.Bf();var f=0;c.length?f=c.length:c.byteLength&&(f=c.byteLength);this.b.zf(f);f=this.b.ad;const a=this.b.$c,b=this.b.bd;if(!(0<f&&"u"===k&&Math.random()<f))if(0===a&&0===b)this.xd(k,c);else{let g=1;"u"!==k&&Math.random()<f&&(g=3);setTimeout(()=>this.xd(k,c),a*g+Math.random()*b*g)}}xd(k,c){try{"o"===k?this.Za&&this.ua&&this.ua.send(c):"r"===k?this.$a&&this.va&&this.va.send(c):"u"===k&&this.ab&&this.wa&&this.wa.send(c)}catch(f){this.qb||(this.b.g()?"o"===k||"r"===k?("string"===
typeof c?(console.error("Error sending "+c.length+"-char string on '"+k+"' to '"+this.K+"', host kicking: ",f),console.log("String that failed to send from previous error was: "+c)):console.error("Error sending "+(c.length||c.byteLength)+"-byte binary on '"+k+"' to '"+this.K+"', host kicking: ",f),this.D("network error")):(this.Jb++,10<=this.Jb&&("string"===typeof c?(console.error("Too many errors ("+this.Jb+") sending data on '"+k+"' to '"+this.K+"', kicking; last error was for sending "+c.length+
"-char string: ",f),console.log("String that failed to send from previous error was: "+c)):console.error("Too many errors ("+this.Jb+") sending data on '"+k+"' to '"+this.K+"', kicking; last error was for sending "+(c.length||c.byteLength)+"-byte binary: ",f),this.D("network error"))):console.error("Error sending data on '"+k+"': ",f))}}oc(k,c){this.qb||(!c&&!this.ic()&&this.o&&25E3<k-this.Rd?(console.warn("Timed out '"+this.K+"', could not establish connection after 25sec"),this.D("timeout")):!c&&
this.ic()&&2E4<k-this.Qc?(console.warn("Timed out '"+this.K+"', not heard from for 20sec"),this.D("timeout")):(this.Wd=k,this.Hc=!0,this.Rc++,this.na("u","ping:"+this.Rc)))}hf(k){k="pong:"+k.substr(5);this.b.g()&&(k=k+"/"+Math.round(performance.now()).toString());this.na("u",k)}Bg(k){if(this.Hc){var c=k.indexOf(":");if(-1<c){if(parseFloat(k.substr(c+1))===this.Rc){c=performance.now();this.Hc=!1;var f=(c-this.Wd)/2;this.Ob.push(f);10<this.Ob.length&&this.Ob.shift();v.push(...this.Ob);v.sort((r,w)=>
r-w);this.be=v[v.length-1]-v[0];var a=0,b=v.length;4<=v.length&&6>=v.length?(++a,--b):6<v.length&&(a+=2,b-=2);var g=0;for(let r=a;r<b;++r)g+=v[r];this.Qb=g/(b-a);v.length=0;this.b.g()||(a=k.indexOf("/"),-1<a?(k=parseFloat(k.substr(a+1)),isFinite(k)?this.b.ne(k,c,f,this.Qb):console.warn("Invalid host time from pong response")):console.warn("Cannot parse off host time from pong response"))}}else console.warn("Cannot parse off ping ID from pong")}}ug(k,c){const f=this.b.ad,a=this.b.$c,b=this.b.bd;if(!(0<
f&&"u"===k&&Math.random()<f))if(0===a&&0===b)this.wd(k,c);else{let g=1;"u"!==k&&Math.random()<f&&(g=3);setTimeout(()=>this.wd(k,c),a*g+Math.random()*b*g)}}wd(k,c){if(!this.qb){this.Qc=performance.now();this.b.Af();var f=0;c.data.length?f=c.data.length:c.data.byteLength&&(f=c.data.byteLength);this.b.yf(f);if("string"===typeof c.data){if(!(""===c.data.trim()||4>c.data.length))if(k=c.data.substr(0,4),"ping"===k)this.hf(c.data);else if("pong"===k)this.Bg(c.data);else{try{var a=JSON.parse(c.data)}catch(b){this.b.$(this,
b);this.b.g()?(console.error("Error parsing message as JSON for peer '"+this.l+"', host kicking: ",b),this.D("data error")):console.error("Error parsing message as JSON for peer '"+this.l+"': ",b);console.log("String that failed to parse from previous error: "+c.data);return}if(a)try{a.c&&"m"!==a.c?this.gg(a):this.b.yg(this,a)}catch(b){this.b.$(this,b),this.b.g()?(console.error("Error handling message for peer '"+this.l+"', host kicking: ",b),this.D("data error")):console.error("Error handling message for peer '"+
this.l+"': ",b)}}}else{!this.Mc&&this.b.g()&&"u"===k&&(this.Mc=!0,this.b.sf(this.l));try{this.fg(c.data)}catch(b){this.b.$(this,b),this.b.g()?(console.error("Error handling binary update for peer '"+this.l+"', host kicking: ",b),this.D("data error")):console.error("Error handling binary update for peer '"+this.l+"': ",b)}}}}gg(k){switch(k.c){case "disconnect":k.k&&A(this.b,"peer-kicked");var c=!this.b.g()&&!this.g();this.D(k.r);c&&this.b.pc();break;case "hi":this.b.g()||(this.b.A.ta(k.hn),this.b.v.ta(k.n),
this.b.lf(k.d),this.b.qf(k.u),this.b.We(k.objs),this.b.Ve(k.cvs));break;case "j":this.b.g()||(c=new G(this.b,k.i,k.a),c.ta(k.n),this.b.Gd(c));break;case "l":!this.b.g()&&(c=this.b.ub(k.i))&&(c.xb()||this.b.Fd(c,k.r),c.D(k.r));break;default:console.error("Unknown control message from peer '"+this.l+"': "+k.c),this.b.$(this,"unknown control message '"+k.c+"'")}}fg(k){this.b.g()?this.rg(k):this.zg(k)}rg(k){k=new DataView(k);let c=0;var f=k.getUint32(c);c+=4;if(1664249200!==f)console.warn("Rejected packet with incorrect magic number (received '"+
f+"', expected '1664249200'");else if(f=k.getFloat64(c),c+=8,f+=this.Qb,!(3E3<=Math.abs(f-performance.now()))){k.getUint8(c);c+=1;var a=k.getUint8(c);c+=1;var b=[],g=this.b.aa;for(let w=0;w<a;++w)if(w>=g.length)b.push(0);else{var r=g[w];switch(r.qa){case 0:r=k.getFloat64(c);c+=8;break;case 1:r=k.getFloat32(c);c+=4;break;case 2:r=r.yb(k.getInt16(c));c+=2;break;case 3:r=r.yb(k.getUint8(c));c+=1;break;default:r=k.getFloat32(c),c+=4}b.push(r)}this.Cf(f,b)}}Cf(k,c){for(let f=0,a=this.R.length;f<a;++f){const b=
this.R[f];if(b.timestamp===k)return;if(b.timestamp>k){this.R.splice(f,0,new p(k,c));return}}this.R.push(new p(k,c))}oa(k){if(0!==this.R.length){for(;2<this.R.length&&this.R[0]!==this.Y&&this.R[0]!==this.h&&this.R[0]!==this.s;)this.R.shift();if(!(this.s&&this.s.timestamp>k&&this.h&&this.h.timestamp<k)){this.s=null;for(let c=0,f=this.R.length;c<f;++c){const a=this.R[c];if(a.timestamp<=k){if(!this.h||a.timestamp>this.h.timestamp)this.Y=this.h,this.h=a}else{this.s=a;break}}}}}zg(k){k=new DataView(k);
let c=0;var f=k.getUint32(c);c+=4;1664249200!==f?console.warn("Rejected packet with incorrect magic number (received '"+f+"', expected '1664249200'"):(f=k.getUint32(c),c+=4,0===f?this.Xf(k,c):1===f?this.Wf(k,c):console.warn("Ignoring packet with incorrect flags (received "+f+", expected 0 or 1"))}Xf(k,c){const f=k.getFloat64(c);c+=8;const a=k.getUint16(c);c+=2;for(let w=0;w<a;++w){var b=k.getUint16(c);c+=2;var g=k.getUint8(c);c+=1;let z=null,E=0;const F=this.b.pd(b);F?(z=F.S,E=z.length,1===g&&F.gh()):
console.warn("Don't know which object corresponds to NID "+b);b=k.getUint16(c);c+=2;g=k.getUint16(c);c+=2;for(let I=0;I<b;++I){const e=k.getUint16(c);c+=2;if(F){const h=[];let t=c;for(let d=0;d<E;++d){var r=z[d];switch(r.qa){case 0:r=k.getFloat64(t);t+=8;break;case 1:r=k.getFloat32(t);t+=4;break;case 2:r=r.yb(k.getInt16(t));t+=2;break;case 3:r=r.yb(k.getUint8(t));t+=1;break;default:r=k.getFloat32(t),t+=4}h.push(r)}F.cc(f,e,h)}c+=g}}}Wf(k,c){const f=k.getFloat64(c);c+=8;const a=k.getUint16(c);c+=2;
for(let g=0;g<a;++g){var b=k.getUint16(c);c+=2;const r=this.b.pd(b);r||console.warn("Don't know which object corresponds to NID "+b);b=k.getUint16(c);c+=2;for(let w=0;w<b;++w){const z=k.getUint16(c);c+=2;r&&!r.Fa&&(this.b.sg(r,z,f),r.nc(z))}}}D(k,c){if(!this.qb){this.qb=!0;this.ag(k);this.na("o",JSON.stringify({c:"disconnect",r:k,k:!!c}));var f=this.ua,a=this.va,b=this.wa,g=this.o;setTimeout(()=>{q(f);q(a);q(b);q(g)},0);this.o=this.wa=this.va=this.ua=null;this.ab=this.$a=this.Za=!1;this.b.ah(this)}}De(k){k=
k.Sd;if(!this.s&&!this.h)return 0;if(this.s&&!this.h){var c=this.s.data;return 0>k||k>=c.length?0:c[k]}var f=this.b.vb();let a,b;if(!this.s&&this.h){if(this.Y){var g=this.Y.timestamp;c=this.Y.data[k];a=this.h.timestamp;b=this.h.data[k];f>this.h.timestamp+250&&(f=this.h.timestamp+250);g=g===a?0:(f-g)/(a-g);return m.wb(this.b.aa[k].ma(),c,b,g,!0)}c=this.h.data;return 0>k||k>=c.length?0:c[k]}g=this.h.timestamp;c=this.h.data[k];a=this.s.timestamp;b=this.s.data[k];g=g===a?0:(f-g)/(a-g);return m.wb(this.b.aa[k].ma(),
c,b,g,!1)}}self.se=G}"use strict";
{const p=self.kd,m=self.se,l=window.RTCPeerConnection||window.webkitRTCPeerConnection||window.mozRTCPeerConnection||window.msRTCPeerConnection,q=window.RTCSessionDescription||window.webkitRTCSessionDescription||window.mozRTCSessionDescription||window.msRTCSessionDescription,v=window.RTCIceCandidate||window.webkitRTCIceCandidate||window.mozRTCIceCandidate||window.msRTCIceCandidate,G=window.RTCDataChannel||window.webkitRTCDataChannel||window.mozRTCDataChannel||window.msRTCDataChannel,k=[{urls:"stun:stun.l.google.com:19302"}];
let c=!1;const f=[];self.T.ka(class extends self.Ba{constructor(a){super(a,"multiplayer");this.Oc=[];this.G=null;this.O=this.da=!1;this.rh={le:0,version:0,name:"",ie:"",he:""};this.L=this.Lc=this.Kc=this.Vc=this.Wc="";this.ba=[];this.ia=new Map;this.Ha=0;this.Yb=new Set;this.A=this.v=null;this.V=80;this.ib=this.Nc=30;this.Zd=0;this.Aa={sb:0,ke:0,fd:0,je:0,ac:0,ge:0,dd:0,fe:0,$b:0};this.Gb=new ArrayBuffer(262144);this.Ic=new DataView(this.Gb);this.U=[];this.ph=1;this.kb=new Map;this.lb=new Map;this.ad=
this.bd=this.$c=0;this.za=[];this.J=this.ea=0;this.M=this.ja=this.V;this.aa=[];this.Fb=new Map;this.Yc=!1;this.wc(k);setInterval(()=>this.Pf(),2E3);window.addEventListener("unload",()=>this.Qa("quit"));K(this,"get-supported",()=>this.og());K(this,"add-ice-servers",b=>this.wc(b.list));K(this,"simulate-latency",b=>this.nf(b.latency,b.pdv,b.loss));K(this,"set-bandwidth-profile",b=>this.kf(b.updateRate,b.delay));K(this,"tick",b=>this.oa(b));K(this,"alert",b=>this.pe(b));K(this,"signalling-connect",b=>
this.tf(b.url));K(this,"signalling-disconnect",()=>this.ud());K(this,"signalling-login",b=>this.vf(b.alias));K(this,"signalling-join-room",b=>this.uf(b.game,b.instance,b.room,b.maxClients));K(this,"signalling-auto-join-room",b=>this.rf(b.game,b.instance,b.room,b.maxClients,b.lock));K(this,"signalling-leave-room",()=>this.pc());K(this,"signalling-list-game-instances",b=>this.wf(b.game));K(this,"signalling-list-rooms",b=>this.xf(b.game,b.instance,b.which));K(this,"disconnect-room",()=>this.od(!0));
K(this,"peer-send-message",b=>this.$e(b));K(this,"host-broadcast",b=>this.Ye(b));K(this,"kick-peer",b=>this.Ze(b));K(this,"sync-object",b=>this.df(b));K(this,"sync-inst-var",b=>this.cf(b));K(this,"associate-object",b=>this.Xe(b));K(this,"remove-object-id",b=>this.mc(b.uid));K(this,"remove-net-insts",b=>this.af(b));K(this,"remove-object-nid",b=>this.bf(b));K(this,"set-client-state",b=>this.td(b.tag,b.value));K(this,"add-client-input-value",b=>this.me(b.tag,b.precision,b.interp))}Sf(a){return a?"string"===
typeof a?a:"string"===typeof a.message?a.message:"string"===typeof a.details?a.details:"string"===typeof a.data?a.data:"string"===typeof a.type?a.type:"unknown error":"unknown error"}hc(){return this.da&&this.O}Pa(){return this.hc()&&this.L}g(){return this.Pa()&&this.v&&this.A===this.v}ze(){return this.hc()?this.Kc:""}Ae(){return this.hc()?this.Lc:""}Be(){return this.Pa()?this.L:""}nf(a,b,g){this.$c=Math.max(a,0);this.bd=Math.max(b,0);this.ad=Math.max(g,0)}og(){return{isSupported:!(!l||!G)}}tf(a){if(!this.G&&
!this.da){try{this.G=new WebSocket(a,"c2multiplayer")}catch(b){this.G=null;this.sa(b);return}this.G.onopen=()=>{-1===this.G.protocol.indexOf("c2multiplayer")?(this.sa("server does not support 'c2multiplayer' protocol"),this.G.close(1002,"'c2multiplayer' protocol required"),this.G=null,this.da=!1):this.da=!0};this.G.onclose=()=>{this.Jg();this.O=this.da=!1;this.G=null};this.G.onerror=b=>{console.error("Signalling server error: ",b);this.sa(b)};this.G.onmessage=b=>{this.Kg(b)}}}ud(){this.G&&this.da&&
(this.G.close(),this.G=null,this.da=!1)}Kg(a){let b;try{b=JSON.parse(a.data)}catch(g){this.sa(g);return}switch(b.message){case "welcome":this.Wg(b);break;case "login-ok":this.Rg(b);break;case "join-ok":this.Og(b);break;case "leave-ok":this.Qg();break;case "kicked":this.Pg();break;case "peer-joined":this.Tg(b);break;case "peer-quit":this.Ug(b);break;case "icecandidate":this.Mg(b);break;case "offer":this.Sg(b);break;case "answer":this.Lg(b);break;case "instance-list":this.Ng(b);break;case "room-list":this.Vg(b);
break;case "error":this.sa(b.details);break;default:this.sa("received unknown signalling message")}}Le(a){for(const b of this.Oc)if(b.urls===a.urls)return!0;return!1}wc(a){if(a)for(let b of a)"string"===typeof b&&(b={urls:b}),this.Le(b)||(b.hasOwnProperty("url")||(b.url=b.urls),this.Oc.push(b))}sa(a){A(this,"signalling-error",{message:this.Sf(a)})}Jg(){A(this,"signalling-close")}Wg(a){if(1>a.protocolrev||1<a.protocolrev)this.sa("signalling server protocol revision not supported"),this.ud();else{this.Wc=
a.clientid;var b=this.rh;b.le=a.protocolrev;b.version=a.version;b.name=a.name;b.ie=a.operator;b.he=a.motd;this.wc(a.ice_servers);A(this,"signalling-welcome",{myid:this.Wc,sigservinfo:{protocolrev:b.le,version:b.version,name:b.name,operator:b.ie,motd:b.he}})}}Rg(a){this.Vc=a.alias;this.O=!0;A(this,"signalling-login-ok",{myalias:this.Vc})}Ie(){return this.ph++}hd(){if(this.g()){do this.Ha++,65535<this.Ha&&(this.Ha=0);while(this.Yb.has(this.Ha));var a=this.Ha;this.Yb.add(a);return a}}we(a){this.g()&&
this.Yb.delete(a)}Og(a){this.Qa("disconnect");this.Kc=a.game;this.Lc=a.instance;this.L=a.room;this.v=new m(this,this.Wc,this.Vc);a.host?(this.A=this.v,this.Ha=0,this.Yb.clear(),this.A.ta(this.hd())):(this.J=this.ea=this.za.length=0,this.V=80,this.ib=this.Nc=30,this.M=this.ja=this.V,this.A=new m(this,a.hostid,a.hostalias),this.A.md());A(this,"signalling-join-ok",{isHost:!!a.host,hostId:this.A.l,hostAlias:this.A.K,game:this.Kc,gameInstance:this.Lc,room:this.L})}Qg(){this.L="";A(this,"signalling-leave-ok")}Pg(){this.od();
this.L="";A(this,"signalling-kicked")}Tg(a){if(this.O&&this.L&&this.g()){var b=this.ia.get(a.peerid);b&&b.D("rejoin");(new m(this,a.peerid,a.peeralias)).md()}}Ug(a){if(this.O&&this.L&&this.g()){var b=this.ia.get(a.id);b&&b.D(a.reason)}}Mg(a){if(this.O&&this.L){var b=this.ia.get(a.from);b&&b.Df(new v(a.icecandidate))}}Sg(a){if(this.O&&this.L&&!this.g()&&this.v&&this.A&&this.A.Me()&&a.from===this.A.l){var b=this.A.o;b.setRemoteDescription(new q(a.offer)).then(()=>{b.createAnswer().then(g=>{b.setLocalDescription(g);
this.Z({message:"answer",toclientid:this.A.l,answer:g})}).catch(g=>{console.error("Peer error creating answer: ",g);this.$(this.v,"could not create answer to host offer")})}).catch(g=>{console.error("Peer error setting remote description: ",g);this.$(this.v,"could not set remote description")})}}Lg(a){if(this.O&&this.L&&this.g()){var b=this.ia.get(a.from);b&&b.o.setRemoteDescription(new q(a.answer)).catch(g=>{console.error("Host error setting remote description: ",g)})}}Ng(a){A(this,"signalling-instance-list",
{list:a.list})}Vg(a){A(this,"signalling-room-list",{list:a.list})}Z(a){this.G&&this.da&&this.G.send(JSON.stringify(a))}vf(a){this.O||this.Z({message:"login",protocolrev:1,alias:a})}uf(a,b,g,r){this.O&&!this.L&&this.Z({message:"join",game:a,instance:b,room:g,max_clients:r})}rf(a,b,g,r,w){this.O&&!this.L&&this.Z({message:"auto-join",game:a,instance:b,room:g,max_clients:r,lock_when_full:w})}pc(){this.O&&this.Z({message:"leave"})}sf(a){this.O&&this.g()&&this.Z({message:"confirm-peer",id:a})}wf(a){this.G&&
this.da&&this.Z({message:"list-instances",game:a})}xf(a,b,g){this.G&&this.da&&this.Z({message:"list-rooms",game:a,instance:b,which:g})}od(a){this.J=this.ea=this.za.length=0;this.Qa("disconnect");for(const b of this.U)b.ue();a&&this.pc()}Ef(a){this.ba.push(a);this.ia.set(a.l,a);A(this,"add-peer",{id:a.l,alias:a.K})}ah(a){A(this,"remove-peer",{id:a.l});this.g()&&this.we(a.F);const b=this.ba.indexOf(a);-1<b&&this.ba.splice(b,1);this.ia.delete(a.l);this.A===a&&(this.A=null,this.Qa("host quit"));this.v===
a&&(this.v=null,this.L="",this.Qa("disconnect"))}Qa(a){if(!c){for(c=!0;this.ba.length;)this.ba[0].D(a);c=!1}}ub(a){return this.ia.get(a)||null}xe(a){return(a=this.ia.get(a))?a.K:""}Ye(a){const b=a.fromId,g=a.tag,r=a.message;a=a.mode;const w=this.ub(b);this.Na(a,JSON.stringify({c:"m",t:g,f:b,m:r}),w)}Na(a,b,g){if(this.g()){var r=this.ba.slice(0);for(const w of r)w&&w!==this.v&&w!==g&&w.na(a,b)}}Pf(){const a=performance.now();if(this.g()){f.push(...this.ba);for(const b of f)b&&b!==this.v&&b.oc(a,!1);
f.length=0}else this.A&&this.A.oc(a,!1)}oe(a){this.U.push(a);this.lb.set(a.mb,a);this.kb.set(a.F,a)}Je(){const a={};for(const [b,g]of this.kb.entries())a[g.nb]={nid:b,nvs:g.He()};return a}We(a){this.kb.clear();for(const b of this.U)if(a.hasOwnProperty(b.nb.toString())){const g=a[b.nb.toString()];b.ta(g.nid);this.kb.set(g.nid,b);b.pf(g.nvs)}else console.warn("Could not map object SID '"+b.nb+"' - host did not send NID for it"),b.ta(-1)}pd(a){return this.kb.get(a)||null}oa(a){if(!this.Pa())return null;
a=a.dt;const b=performance.now();b-this.Zd>=1E3/(this.g()?this.Nc:this.ib)-5&&(this.jf(b),this.Zd=b);const g=this.Aa;1E3<=b-g.sb&&(g.ke=g.fd,g.je=g.ac,g.ge=g.dd,g.fe=g.$b,g.fd=0,g.ac=0,g.dd=0,g.$b=0,g.sb+=1E3,500<b-g.sb&&(g.sb=b),A(this,"stats",{stats:{outboundPerSec:g.ke,outboundBandwidthPerSec:g.je,inboundPerSec:g.ge,inboundBandwidthPerSec:g.fe}}));this.g()||(this.J<this.ea?(this.J+=10*a,this.J>this.ea&&(this.J=this.ea)):this.J>this.ea&&(this.J-=10*a,this.J<this.ea&&(this.J=this.ea)),this.M<this.ja?
(this.M+=30*a,this.M>this.ja&&(this.M=this.ja)):this.M>this.ja&&(this.M-=30*a,this.M<this.ja&&(this.M=this.ja)));a=this.vb();for(const r of this.ba)r.oa(a);for(const r of this.U)r.oa();return{simulationTime:this.vb(),hostInputArrivalTime:this.Ce(),clientDelay:this.V,peerData:this.Uf(),roData:this.Vf(),isReadyForInput:this.rd()}}Uf(){const a={};for(const b of this.ba){const g={};for(const r of this.aa)g[r.ob]=b.De(r);a[b.l]={nid:b.F,latency:b.Qb,pdv:b.be,clientState:g}}return a}Vf(){const a={};for(const b of this.U)a[b.mb]=
b.Ca();return a}async jf(a){this.g()?(await this.fh(a),this.eh(a)):await this.dh(a)}async dg(){const a=await B(this,"before-client-update");for(const b of a.clientStateUpdates)this.td(b.tag,b.value)}async dh(a){this.rd()&&await this.dg();if(this.v&&this.Yc){var b=this.Ic,g=0,r=this.aa,w=this.v.ae,z=a-this.v.Xd,E=a-this.v.Yd;if(100>z||(1E3>z?95<=E:495<=E)){b.setUint32(g,1664249200);g+=4;b.setFloat64(g,a+this.J);g+=8;b.setUint8(g,0);g+=1;b.setUint8(g,r.length);g+=1;for(let F=0,I=r.length;F<I;++F)z=
r[F],E=0,F<w.length&&(E=z.ld(w[F])),g=z.vd(b,g,E);this.v.ih(a);this.A.na("u",new Uint8Array(this.Gb.slice(0,g)))}}}async fh(a){const b=this.Ic;let g=0,r=0;const w=await B(this,"get-object-info",{ros:this.U.map(z=>z.Ke())});for(const z of this.U){const E=z.mb;w.hasOwnProperty(E)&&(z.qc(w[E],a),0<z.hb&&r++)}if(0!==r){b.setUint32(g,1664249200);g+=4;b.setUint32(g,0);g+=4;b.setFloat64(g,a);g+=8;b.setUint16(g,r);g+=2;for(const z of this.U)0<z.hb&&(g=z.rc(b,g,a));this.Na("u",new Uint8Array(this.Gb.slice(0,
g)),null)}}eh(a){const b=this.Ic;let g=0,r=0;for(const w of this.U)w.Hb.length&&r++;if(0!==r){b.setUint32(g,1664249200);g+=4;b.setUint32(g,1);g+=4;b.setFloat64(g,a);g+=8;b.setUint16(g,r);g+=2;for(const w of this.U)if(a=w.Hb,a.length){b.setUint16(g,w.F);g+=2;b.setUint16(g,a.length);g+=2;for(const z of a)b.setUint16(g,z),g+=2;a.length=0}this.Na("r",new Uint8Array(this.Gb.slice(0,g)),null)}}ne(a,b,g,r){if(!this.g()){this.ja=r+this.V;a=a+g-b;0===this.za.length&&(this.J=a,this.M=this.ja);this.za.push(a);
30<this.za.length&&this.za.shift();f.push(...this.za);f.sort((w,z)=>w-z);a=0;b=f.length;4<=f.length&&6>=f.length?(++a,--b):6<f.length&&19>=f.length?(a+=2,b-=2):19<f.length&&(a+=5,b-=5);g=0;for(r=a;r<b;++r)g+=f[r];this.ea=g/(b-a);f.length=0}}vb(){return this.g()?performance.now()-this.V:performance.now()+this.J-this.M}Ce(){return this.g()?performance.now():performance.now()+this.J+this.M}td(a,b){if(!this.g()&&this.v&&this.Yc&&(a=this.Fb.get(a))){a=a.Sd;var g=this.v.ae;g.length<a+1&&(g.length=a+1);
g[a]!==b&&(g[a]=b,this.v.hh())}}me(a,b,g){b=new p(this.aa.length,g,b,a,null);this.Fb.set(a,b);this.aa.push(b)}ye(){const a=[];for(const b of this.aa)a.push({tag:b.ob,precision:b.qa,interp:b.ma()});return a}Ve(a){this.Fb.clear();this.aa.length=0;for(let g=0,r=a.length;g<r;++g){var b=a[g];b=new p(g,b.interp,b.precision,b.tag,null);this.Fb.set(b.ob,b);this.aa.push(b)}this.Yc=!0}mc(a){for(const b of this.U)b.mc(a)}rd(){return this.Pa()?this.g()?!0:0!==this.ea:!1}kf(a,b){this.Pa()||(this.ib=this.Nc=a,
this.V=b)}Gd(a){A(this,"peer-open",{id:a.l,alias:a.K})}$e(a){const b=a.tag,g=a.message,r=a.mode;(a=this.ub(a.id))&&a.na(r,JSON.stringify({c:"m",t:b,m:g}))}Fd(a,b){A(this,"peer-close",{id:a.l,alias:a.K,reason:b||"unknown"})}$(a,b){console.error(`[Multiplayer] Peer '${a.K}' (${a.l}) error: `,b)}yg(a,b){a=b.f||a.l;A(this,"peer-message",{tag:b.t,fromId:a,fromAlias:this.xe(a),content:b.m})}sg(a,b,g){A(this,"instance-destroyed",{roId:a.mb,nid:b,timestamp:g})}Ze(a){if(this.g()){var b=a.reason;(a=this.ub(a.id))&&
a.D(b,!0)}}Bf(){this.Aa.fd++}zf(a){this.Aa.ac+=a}Af(){this.Aa.dd++}yf(a){this.Aa.$b+=a}lf(a){this.V=a}qf(a){this.ib=a}df(a){const b=a.data,g=a.precision,r=a.bandwidth;for(const w of a.objectClasses)a=new self.te(this,w.roId,w.sid,r),1===b?(a.la(1,g,"x"),a.la(1,g,"y")):2===b?a.la(2,g,"a"):3===b&&(a.la(1,g,"x"),a.la(1,g,"y"),a.la(2,g,"a"))}pe(a){alert(a.message)}cf(a){const b=a.precision,g=a.interp,r=a.cvt;for(const w of a.syncData)this.lb.get(w.roId).la(g,b,"iv",w.varIndex,r)}Xe(a){var b=a.peerId;
const g=a.instUid;a=this.lb.get(a.roId);b=this.ia.get(b);a&&b&&this.g()&&a.ef(g,b.F)}af(a){for(const [b,g]of Object.entries(a))if(a=this.lb.get(parseInt(b,10)))for(const r of g)a.nc(r)}bf(a){const b=a.nid;(a=this.lb.get(a.roId))&&a.nc(b)}})}"use strict";
{function p(l){l.stopPropagation()}function m(l){13!==l.which&&27!==l.which&&l.stopPropagation()}self.T.ka(class extends self.fc{constructor(l){super(l,"text-input");P(this,"scroll-to-bottom",q=>this.Hg(q))}tb(l,q){let v;const G=q.type;"textarea"===G?(v=document.createElement("textarea"),v.style.resize="none"):(v=document.createElement("input"),v.type=G);v.style.position="absolute";v.autocomplete="off";v.addEventListener("touchstart",p);v.addEventListener("touchmove",p);v.addEventListener("touchend",
p);v.addEventListener("mousedown",p);v.addEventListener("mouseup",p);v.addEventListener("keydown",m);v.addEventListener("keyup",m);v.addEventListener("click",k=>{k.stopPropagation();Q(this,"click",l)});v.addEventListener("dblclick",k=>{k.stopPropagation();Q(this,"dblclick",l)});v.addEventListener("input",()=>O(this,"change",l,{text:v.value}));q.id&&(v.id=q.id);this.ra(v,q);return v}ra(l,q){l.value=q.text;l.placeholder=q.placeholder;l.title=q.title;l.disabled=!q.isEnabled;l.readOnly=q.isReadOnly;l.spellcheck=
q.spellCheck;q=q.maxLength;0>q?l.removeAttribute("maxlength"):l.setAttribute("maxlength",q)}Hg(l){l.scrollTop=l.scrollHeight}})}"use strict";
{function p(m){m.stopPropagation()}self.T.ka(class extends self.fc{constructor(m){super(m,"button")}tb(m,l){const q=document.createElement("input");var v=q;l.isCheckbox?(q.type="checkbox",v=document.createElement("label"),v.appendChild(q),v.appendChild(document.createTextNode("")),v.style.fontFamily="sans-serif",v.style.userSelect="none",v.style.webkitUserSelect="none",v.style.display="inline-block",v.style.color="black"):q.type="button";v.style.position="absolute";v.addEventListener("touchstart",
p);v.addEventListener("touchmove",p);v.addEventListener("touchend",p);v.addEventListener("mousedown",p);v.addEventListener("mouseup",p);v.addEventListener("keydown",p);v.addEventListener("keyup",p);q.addEventListener("click",()=>Q(this,"click",m,{isChecked:q.checked}));l.id&&(q.id=l.id);this.ra(v,l);return v}Ad(m){return"input"===m.tagName.toLowerCase()?m:m.firstChild}tc(m){return this.Ad(m)}ra(m,l){const q=this.Ad(m);q.checked=l.isChecked;q.disabled=!l.isEnabled;m.title=l.title;m===q?q.value=l.text:
m.lastChild.textContent=l.text}})}"use strict";
self.T.ka(class extends self.Ba{constructor(p){super(p,"mouse");L(this,[["cursor",m=>{document.documentElement.style.cursor=m}],["request-pointer-lock",()=>{this.B.N.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{A(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{A(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
"use strict";function V(p){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(m=>A(p,"sw-message",m.data))}
function W(p){p=p.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(p).catch(m=>console.warn("[Construct 3] Failed to lock orientation: ",m));else try{let m=!1;screen.lockOrientation?m=screen.lockOrientation(p):screen.webkitLockOrientation?m=screen.webkitLockOrientation(p):screen.mozLockOrientation?m=screen.mozLockOrientation(p):screen.msLockOrientation&&(m=screen.msLockOrientation(p));m||console.warn("[Construct 3] Failed to lock orientation")}catch(m){console.warn("[Construct 3] Failed to lock orientation: ",
m)}}
self.T.ka(class extends self.Ba{constructor(p){super(p,"browser");this.j="";L(this,[["get-initial-state",m=>{this.j=m.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>V(this)],
["alert",m=>this.xc(m)],["close",()=>this.zc()],["set-focus",m=>this.Dc(m)],["vibrate",m=>{navigator.vibrate&&navigator.vibrate(m.pattern)}],["lock-orientation",m=>W(m)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(m){}}],
["navigate",m=>{var l=m.type;if("back"===l)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===l)window.history.forward();else if("reload"===l)location.reload();else if("url"===l){l=m.url;const q=m.target;m=m.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(l,"_system"):"preview"===m||"windows-webview2"===m?window.open(l,"_blank"):this.Lh||(2===q?window.top.location=l:1===q?window.parent.location=l:window.location=
l)}else"new-window"===l&&(l=m.url,m=m.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(l,"_system"):window.open(l,m))}],["request-fullscreen",m=>{if("windows-webview2"===this.j||"macos-wkwebview"===this.j)self.T.Db(!0),this.B.Gc({type:"set-fullscreen",fullscreen:!0});else{const l={navigationUI:"auto"};m=m.navUI;1===m?l.navigationUI="hide":2===m&&(l.navigationUI="show");m=document.documentElement;m.requestFullscreen?m.requestFullscreen(l):m.mozRequestFullScreen?m.mozRequestFullScreen(l):
m.msRequestFullscreen?m.msRequestFullscreen(l):m.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?m.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):m.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.j||"macos-wkwebview"===this.j?(self.T.Db(!1),this.B.Gc({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():
document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",m=>{location.hash=m.hash}]]);window.addEventListener("online",()=>{A(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{A(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{A(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{A(this,"backbutton")})}xc(p){alert(p.message)}zc(){navigator.app&&navigator.app.exitApp?navigator.app.exitApp():
navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}Dc(p){p=p.isFocus;if("nwjs"===this.j){const m="nwjs"===this.j?nw.Window.get():null;p?m.focus():m.blur()}else p?window.focus():window.blur()}});"use strict";
self.T.ka(class extends self.Ba{constructor(p){super(p);var m=this;K(this,"doAction",function(l){if("setlocal"===l.action)localStorage.setItem(l.uh,l.Mh);else if("getlocal"===l.action){var q=localStorage.getItem("ExtImg-"+l.Ch+l.xh);A(m,"on_complete",null!==q?{blob_text:q,obj_name:l.Ch,img_id:l.xh,myObj:l.Bh,action:"getlocal",err:!1}:{action:"getlocal",myObj:l.Bh,err:!0})}else"deletelocal"===l.action&&localStorage.removeItem(l.uh)})}});"use strict";
{function p(m){m.stopPropagation()}self.T.ka(class extends self.fc{constructor(m){super(m,"file-chooser");P(this,"click",l=>this.Kf(l));P(this,"clear",l=>this.Jf(l))}tb(m,l){const q=document.createElement("input");q.type="file";q.style.position="absolute";q.style.userSelect="none";q.style.webkitUserSelect="none";q.addEventListener("touchstart",p);q.addEventListener("touchmove",p);q.addEventListener("touchend",p);q.addEventListener("mousedown",p);q.addEventListener("mouseup",p);q.addEventListener("change",
()=>O(this,"change",m,{files:Array.from(q.files)}));l.id&&(q.id=l.id);this.ra(q,l);return q}ra(m,l){m.setAttribute("accept",l.accept);l.isMultiSelect?m.setAttribute("multiple",""):m.removeAttribute("multiple")}Kf(m){m.click()}Jf(m){m.value=""}})};
